baseURL = 'https://smbl64.github.io'
languageCode = 'en-us'
title = 'Mohammad Banisaeid'
theme = 'm10c'
publishDir = "docs"

[params]
author = "Mohammad Banisaeid"
description = "My notes on tech and whatnot!"

[[params.social]]
  icon = "github"
  name = "GitHub"
  url = "https://github.com/smbl64"

[[params.social]]
  icon = "linkedin"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/mbanisaeid/"
