baseURL = 'https://smbl64.github.io'
languageCode = 'en-us'
title = 'Mohammad Banisaeid'
theme = 'PaperMod'

[params]
author = "Mohammad Banisaeid"
description = "My notes on tech and whatnot!"

github = "smbl64"
linkedin = "mbanisaeid"
[params.homeInfoParams]
Title = "Hi there wave"
Content = "Some content"

[[params.homeInfoParams.socialIcons]]
name = "github"
url = "https://wwwad.asdasdasd.com"
